describe('Auth Update Account', () => {
  it('sukses_updateaccount_firstlastname', () => {
    cy.visit('https://magento.softwaretestingboard.com')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('#email').type("herdiantesting6@gmail.com")
    cy.get('#pass').type("123123qwe@@")
    cy.wait(30)
    cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
    cy.wait(30)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click({force: true})
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.get('#firstname').type("1")
    cy.get('#lastname').type("1")
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.get('.message-success').should('be.visible')
  })

  it('sukses_updateaccount_email', () => {
    cy.visit('https://magento.softwaretestingboard.com')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('#email').type("herdiantesting6@gmail.com")
    cy.get('#pass').type("123123qwe@@")
    cy.wait(30)
    cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
    cy.wait(30)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click({force: true})
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.get('#change-email').click()
    cy.get('#email').type("{selectAll}HerdianGanti6@gmail.com")
    cy.get('#current-password').type("123123qwe@@")
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.get('.message-success').should('be.visible')
  })

  it('sukses_updateaccount_password', () => {
    cy.visit('https://magento.softwaretestingboard.com')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('#email').type("herdianGanti6@gmail.com")
    cy.get('#pass').type("123123qwe@@")
    cy.wait(30)
    cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
    cy.wait(30)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click({force: true})
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.get('#change-password').click()
    cy.get('#current-password').type("123123qwe@@")
    cy.get('#password').type("12345qwe@@")
    cy.get('#password-confirmation').type("12345qwe@@")
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.get('.message-success').should('be.visible')
  })

  it('failed_updateaccount_email', () => {
    cy.visit('https://magento.softwaretestingboard.com')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('#email').type("herdiantesting3@gmail.com")
    cy.get('#pass').type("123123qwe@@")
    cy.wait(30)
    cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
    cy.wait(30)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click({force: true})
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.get('#change-email').click()
    cy.get('#email').type("{selectAll}testing@gmail.com")
    cy.get('#current-password').type("123123qwe@@")
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.get('.message-error').should('be.visible')
  })

  it('failed_updateaccount_invalidcurrentpassword', () => {
    cy.visit('https://magento.softwaretestingboard.com')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('#email').type("herdiantesting3@gmail.com")
    cy.get('#pass').type("123123qwe@@")
    cy.wait(30)
    cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
    cy.wait(30)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click({force: true})
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.get('#change-password').click()
    cy.get('#current-password').type("123123")
    cy.get('#password').type("12345qwe@@")
    cy.get('#password-confirmation').type("12345qwe@@")
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.get('.message-error').should('be.visible')
  })

  it('failed_updateaccount_blankfield', () => {
    cy.visit('https://magento.softwaretestingboard.com')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('#email').type("herdiantesting3@gmail.com")
    cy.get('#pass').type("123123qwe@@")
    cy.wait(30)
    cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
    cy.wait(30)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click({force: true})
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.get('#change-password').click()
    cy.get('#current-password').click()
    cy.get('#password').click()
    cy.get('#password-confirmation').click()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.get('#current-password-error').should('be.visible')
  })

})